apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.strategy.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.strategy.rollingUpdate.maxUnavailable }}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ADFS_AUTH_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.adfsAuthEnabled
        - name: ADFS_ISSUER_THUMBPRINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.adfsIssuerThumbprint
        - name: ADFS_ISSUER_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.adfsIssuerUri
        - name: DATABASE_COLLECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.databaseCollectionName
        - name: DATABASE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.databaseEndpoint
        - name: DATABASE_KEY
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.databaseKey
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.databaseName
        - name: DD_APPLICATION_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.ddApplicationId
        - name: DD_CLIENT_TOKEN
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.ddClientToken
        - name: DD_RUM_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.ddRumEnabled
        - name: DD_TRACE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.ddTraceEnabled
        - name: DEBUG_FLAGS
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.debugFlags
        - name: DEVELOPER_MODE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.developerModeEnabled
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.environment
        - name: FEATURE_TOGGLE_EXCEPTION_VALIDITY_WINDOW
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.featureToggleExceptionValidityWindow
        - name: FEATURE_TOGGLE_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.featureToggleServiceUri
        - name: GTM_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.gtmEnabled
        - name: GTM_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.gtmId
        - name: HOME_PROTECT_HOMEPAGE_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.homeProtectHomepageEnabled
        - name: HOTJAR_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.hotjarEnabled
        - name: HOTJAR_ID
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.hotjarId
        - name: HOTJAR_TRACKING_CODE
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.hotjarTrackingCode
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.namespace
        - name: NODEJS_CONFIG_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.configEnvironment
        - name: OPTIMISATION_ENABLED
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.optimisationEnabled
        - name: PUBLIC_URL
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.endpoint
        - name: QUOTE_AND_BUY_SERVICE_URI
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.quoteAndBuyServiceUri
        - name: RELEASE_VERSION
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.releaseVersion
        - name: SCHEME_AND_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.schemeAndHost
        - name: SERVE_STATIC_CONTENT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.serveStaticContent
        - name: SERVER_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.port
        - name: USE_FILE_PERSISTENCE
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.useFilePersistence
        - name: USE_SECURE_SERVER
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.useSecureServer
        - name: VERBOSE_LOGGING
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.logging.verbose
        - name: WEBSITE_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: {{ .Chart.Name }}-config
              key: app.endpoint
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - containerPort: {{ .Values.service.port }}
