apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: {{ .Values.app.namespace }}
  name: {{ .Chart.Name }}-{{ .Values.app.environment }}-virtualservice
spec:
  hosts:
  - {{ .Values.istio.hostname }}
  gateways:
  - istio-system/{{.Values.istio.gateWayType}}gateway-{{ .Values.app.environment }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 80
